### ISSUE TITLE
does this provider have dns support?

### ISSUE THREAD

**Issue by edwmurph** [zerotier/terraform-zerotier-network#2]
is there a way to declaratively configure dns mappings for a zerotier network via terraform?

<img width="598" alt="image" src="https://user-images.githubusercontent.com/20996513/231919673-81902f3b-618a-4984-995f-29f8fb51b735.png">

**Comment by laduke** [comment]
https://github.com/zerotier/zeronsd will use the member names for dns names. 

Otherwise I think you'd use a different provider to shove your dns names into your dns server.

**Comment by edwmurph** [comment]
the screenshot i posted above is from the zerotier UI. i believe it enables overrides for the ip address of the dns server to use for certain domains. this terraform-zerotier-network provider allows configuring all the other sections for networks in the zerotier UI. can support be added for the DNS section as well?

**Comment by someara** [comment]
I believe this should be possible... we'd have to add it to the underlying "zerotier_network" provider.
I can take a look this week.

-s

**Comment by someara** [comment]
Support was added in this PR https://github.com/zerotier/terraform-zerotier-network/pull/3 and released as 1.5.0
-s
